### ISSUE TITLE
Tomcat installation often failing on GitHub Actions

### ISSUE THREAD

**Issue by davidpcaldwell** [davidpcaldwell/slime#1799]
Seems to be connection timeout; should we solve it by updating? By increasing connection timeout? Will it pass?

```
[jsh] /slime/rhino/http/client/module.js:183: Wrapped java.net.ConnectException: Connection timed out (Connection timed out) (/slime/rhino/http/client/module.js#183)
org.mozilla.javascript.WrappedException: Wrapped java.net.ConnectException: Connection timed out (Connection timed out) (/slime/rhino/http/client/module.js#183)
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1860)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:234)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:211)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1896)
	at script(/slime/rhino/http/client/module.js:183)
	at script(/slime/rhino/http/client/module.js:355)
	at script(slime://loader/events.js:222)
	at script(slime://loader/$api-fp-impure.js:217)
	at script.oldspi(/slime/rhino/http/client/objects.js:191)
	at script.request(/slime/rhino/http/client/objects.js:234)
	at script(/slime/rhino/http/client/objects.js:306)
	at script(/slime/jrunscript/tools/install/deprecated.js:40)
	at script(/slime/jrunscript/tools/install/deprecated.js:75)
	at script(slime://loader/events.js:175)
	at script(/slime/jrunscript/tools/install/apache.js:43)
	at script(slime://loader/events.js:222)
	at script(slime://loader/$api-fp-impure.js:443)
	at script(/slime/jrunscript/jsh/tools/install/tomcat.js:210)
	at script(/slime/jrunscript/jsh/tools/install/tomcat.js:276)
	at script(slime://loader/events.js:222)
	at script(slime://loader/$api-fp-impure.js:449)
	at script(/slime/jrunscript/jsh/tools/install/tomcat.js:321)
	at script(/slime/contributor/suite.jsh.js:17)
```

**Comment by davidpcaldwell** [comment]
Put attempt in place, see above, to resolve this problem. If it works for a while, we can close this.

**Comment by davidpcaldwell** [comment]
Looks like this can also happen when executing built shell, specifically running the `tomcat.jsh.js` script; should make that retryable also.

**Comment by davidpcaldwell** [comment]
No failures in quite a while; closing.
