### ISSUE TITLE
In devcontainer, tool installs fail

### ISSUE THREAD

**Issue by davidpcaldwell** [davidpcaldwell/slime#452]
See below error. An analogous error happens for Rhino.

In theory, this may be because we are attempting to write to a Docker volume here. The same code seems to work inside GitHub Actions.

As a workaround, using the `mv` command after the error to move the file where it was trying to move it succeeds, for unknown reasons.

```
root@e54ca0f39833:/slime# ./fifty test.jsh rhino/shell/module.fifty.ts 
java.lang.RuntimeException: java.io.IOException: Failed to move: /tmp/slime3813334804388148718.tmp/node-v16.13.1-linux-x64 to /slime/local/jsh/lib/node
        at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:397)
        at jdk.nashorn.internal.scripts.Script$Recompilation$33$4303AAAA$nashorn.L:19#nashorn#compile(slime://loader/jrunscript/nashorn.js:109)
        at jdk.nashorn.internal.scripts.Script$Recompilation$31$5603AAAA$nashorn.L:19#nashorn#script(slime://loader/jrunscript/nashorn.js:139)
        at jdk.nashorn.internal.scripts.Script$Recompilation$30$10914AAAA$nashorn.L:19#$javahost#script(slime://loader/jrunscript/nashorn.js:269)
        at jdk.nashorn.internal.scripts.Script$Recompilation$48$3642AAA$expression.L:18#slime#execute(slime://loader/jrunscript/expression.js:112)
        at jdk.nashorn.internal.scripts.Script$Recompilation$124$2631AA$scripts.L:19#run(slime://loader/scripts.js:131)
        at jdk.nashorn.internal.scripts.Script$Recompilation$120$7866AAA$expression.L:13#topMethod#L:331(slime://loader/expression.js:332)
        at jdk.nashorn.internal.scripts.Script$Recompilation$855$jsh.L:16#jsh#loader#run(/slime/jsh/loader/jsh.js:242)
        at jdk.nashorn.internal.scripts.Script$Recompilation$854$16139AAA$plugin_jsh.L:18#load-2#L:514#L:515#L:516(/slime/jsh/script/plugin.jsh.js:533)
        at jdk.nashorn.internal.scripts.Script$Recompilation$151$485AAAA$jsh.L:16(/slime/jsh/loader/jsh.js:416)
        at jdk.nashorn.internal.scripts.Script$150$jsh.:program(/slime/jsh/loader/jsh.js:8)
        at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
        at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
        at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
        at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
        at inonit.script.engine.Host$JavaxScriptHost.eval(Host.java:95)
        at inonit.script.engine.Host.run(Host.java:118)
        at inonit.script.engine.Host.run(Host.java:127)
        at inonit.script.jsh.Shell$Execution$1.run(Shell.java:727)
        at inonit.script.jsh.Nashorn$ExecutionImpl$ErrorHandlingImpl.run(Nashorn.java:112)
        at inonit.script.jsh.Shell$Execution.execute(Shell.java:724)
        at inonit.script.jsh.Nashorn.main(Nashorn.java:40)
        at inonit.script.jsh.Shell$Engine.shell(Shell.java:646)
        at inonit.script.jsh.Main.cli(Main.java:536)
        at inonit.script.jsh.Nashorn.main(Nashorn.java:136)
Caused by: java.io.IOException: Failed to move: /tmp/slime3813334804388148718.tmp/node-v16.13.1-linux-x64 to /slime/local/jsh/lib/node
        at inonit.script.runtime.io.Filesystem$NativeFilesystem$NodeImpl.move(Filesystem.java:302)
        at jdk.nashorn.internal.scripts.Script$Recompilation$951$8171AA$java.L:17#FilesystemProvider#move(/slime/rhino/file/java.js:287)
        at jdk.nashorn.internal.scripts.Script$Recompilation$948$9547AA$file.L:16#Pathname#Node#move(/slime/rhino/file/file.js:342)
        at jdk.nashorn.internal.scripts.Script$Recompilation$884$4840AA$module.L:15#installLocalArchive(/slime/jrunscript/tools/install/module.js:175)
        at jdk.nashorn.internal.scripts.Script$Recompilation$881$6871AA$module.L:15#install(/slime/jrunscript/tools/install/module.js:200)
        at jdk.nashorn.internal.scripts.Script$Recompilation$880$7187AA$module.L:15#oldInstall(/slime/jrunscript/tools/install/module.js:204)
        at jdk.nashorn.internal.scripts.Script$Recompilation$863$4221AA$events.L:14#listening#L:161(slime://loader/events.js:174)
        at jdk.nashorn.internal.scripts.Script$Recompilation$878$8809AA$module.L:15#install-1(/slime/jrunscript/tools/install/module.js:258)
        at jdk.nashorn.internal.scripts.Script$Recompilation$877$7903AA$module.L:14#install(/slime/rhino/tools/node/module.js:275)
        at jdk.nashorn.internal.scripts.Script$Recompilation$863$4221AA$events.L:14#listening#L:161(slime://loader/events.js:174)
        at jdk.nashorn.internal.scripts.Script$Recompilation$874$21701A$plugin_jsh.L:16#load-1#integratedNode#install(/slime/jsh/tools/install/plugin.jsh.js:712)
        at jdk.nashorn.internal.scripts.Script$Recompilation$873$21374$plugin_jsh.L:16#load-1#integratedNode#require#install(/slime/jsh/tools/install/plugin.jsh.js:693)
        at jdk.nashorn.internal.scripts.Script$Recompilation$867$17567AA$jsh.L:17#require(/slime/rhino/shell/jsh.js:542)
        at jdk.nashorn.internal.scripts.Script$Recompilation$863$4221AA$events.L:14#listening#L:161(slime://loader/events.js:174)
        at jdk.nashorn.internal.scripts.Script$Recompilation$862$21218$plugin_jsh.L:16#load-1#integratedNode#require(/slime/jsh/tools/install/plugin.jsh.js:688)
        at jdk.nashorn.internal.scripts.Script$Recompilation$861$16497A$plugin_jsh.L:16#load#typescript#require(/slime/tools/wf/plugin.jsh.js:520)
        at jdk.nashorn.internal.scripts.Script$Recompilation$860$347AA$test_jsh.L:13(/slime/tools/fifty/test.jsh.js:14)
        at jdk.nashorn.internal.scripts.Script$859$test_jsh.:program(/slime/tools/fifty/test.jsh.js:8)
        at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
        at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
        at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
        ... 27 more
```

**Comment by davidpcaldwell** [comment]
Should retest this with experimental filesystem on and off on macOS.
