### ISSUE TITLE
Get VSCode Java language server working with JDK 17

### ISSUE THREAD

**Issue by davidpcaldwell** [davidpcaldwell/slime#596]
In devcontainer, currently getting this:
```
WARNING: Using incubator modules: jdk.incubator.foreign, jdk.incubator.vector
[Error - 1:25:52 AM] Jul 10, 2022, 1:25:52 AM An internal error occurred during: "Loading available Gradle versions".
null
java.lang.ExceptionInInitializerError
	at java.base/javax.crypto.Cipher.getInstance(Cipher.java:546)
	at java.base/sun.security.ssl.SSLCipher.isTransformationAvailable(SSLCipher.java:511)
	at java.base/sun.security.ssl.SSLCipher.<init>(SSLCipher.java:500)
	at java.base/sun.security.ssl.SSLCipher.<clinit>(SSLCipher.java:82)
	at java.base/sun.security.ssl.CipherSuite.<clinit>(CipherSuite.java:65)
	at java.base/sun.security.ssl.SSLContextImpl.getApplicableSupportedCipherSuites(SSLContextImpl.java:343)
	at java.base/sun.security.ssl.SSLContextImpl$AbstractTLSContext.<clinit>(SSLContextImpl.java:556)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at java.base/java.security.Provider$Service.getImplClass(Provider.java:1933)
	at java.base/java.security.Provider$Service.getDefaultConstructor(Provider.java:1964)
	at java.base/java.security.Provider$Service.newInstanceOf(Provider.java:1878)
	at java.base/java.security.Provider$Service.newInstanceUtil(Provider.java:1886)
	at java.base/java.security.Provider$Service.newInstance(Provider.java:1861)
	at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
	at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
	at java.base/javax.net.ssl.SSLContext.getInstance(SSLContext.java:185)
	at java.base/javax.net.ssl.SSLContext.getDefault(SSLContext.java:110)
	at java.base/javax.net.ssl.SSLSocketFactory.getDefault(SSLSocketFactory.java:83)
	at java.base/javax.net.ssl.HttpsURLConnection.getDefaultSSLSocketFactory(HttpsURLConnection.java:336)
	at java.base/javax.net.ssl.HttpsURLConnection.<init>(HttpsURLConnection.java:292)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.<init>(HttpsURLConnectionImpl.java:81)
	at java.base/sun.net.www.protocol.https.Handler.openConnection(Handler.java:62)
	at java.base/sun.net.www.protocol.https.Handler.openConnection(Handler.java:57)
	at java.base/java.net.URL.openConnection(URL.java:1094)
	at org.eclipse.buildship.core.internal.util.gradle.PublishedGradleVersions.downloadVersionInformation(PublishedGradleVersions.java:159)
```
But on macOS host, also having problems, apparently with the language server sending an unrecognized option to the JVM when trying to create the JVM. Could it be Corretto-specific? Or is it version-specific?
```
Caused by: org.gradle.api.GradleException: Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the User Manual chapter on the daemon at https://docs.gradle.org/7.4.2/userguide/gradle_daemon.html
Process command line: /Users/inonit/.inonit/tool/vscode/jdk/Contents/Home/bin/java -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED --add-opens java.base/java.nio.charset=ALL-UNNAMED --add-opens java.base/java.net=ALL-UNNAMED --add-opens java.base/java.util.concurrent.atomic=ALL-UNNAMED -Xmx2048M -Dfile.encoding=utf8 -Duser.country=US -Duser.language=en -Duser.variant -cp /Users/inonit/.gradle/wrapper/dists/gradle-7.4.2-bin/48ivgl02cpt2ed3fh9dbalvx8/gradle-7.4.2/lib/gradle-launcher-7.4.2.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 7.4.2
Please read the following process output to find out more:
-----------------------
Unrecognized VM option 'MaxPermSize=512m'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by davidpcaldwell** [comment]
Problem appears to be upstream: https://github.com/redhat-developer/vscode-java/issues/2551

Moving to 0.0.5.3 for now.

**Comment by davidpcaldwell** [comment]
May be able to use a setting to fix this. See the upstream issue for details.
